# Exercise 4.7 Data & Aggregating Variables

# Exercise Practice

## Step 1 Preparing environment

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# Create path

path =  r"C:\Users\leobs\OneDrive\Data Program\Achievement 4_Instacart\Instacart Basket Analysis"

In [3]:
# Import dataframe, with new name as ords_prods_merge

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merged.pkl'))

In [4]:
# Check import

ords_prods_merge.head()

# Successful import with updates from 4.7

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders

## Create subset of data

In [6]:
# Subset for first 1000000

df = ords_prods_merge[:1000000]

In [7]:
# Check shape

df.shape

(1000000, 18)

In [8]:
df.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders

## Grouping data with pandas

In [9]:
# Groupby() test

df.groupby('product_name')

# As noted, will not show output

In [12]:
# Aggregate data with agg()

df.groupby('department_id').agg({'order_number': ['mean']})

# Finds average number of orders per department

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [13]:
# Another way with same results

df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [14]:
# Perform multipl aggregations for descriptive stats

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

# same min and max sometimes occur because clients pre-set min and max parameters

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

## Aggregating with transform and creating loyalty flag using loc

In [15]:
# Group data, transform, and create a new column for customer order max values

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [16]:
# Check output

ords_prods_merge.head(50)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24

In [17]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22

In [ ]:
# Command to not assign any options regarding the maximum number of rows to display, to help check aggregation

pd.options.display.max_rows = None

# Can delete output later

In [19]:
ords_prods_merge.head(100)

# Still unsure about how this changes the output, for example user id 15 does not have 27 rows even though their max is 27

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,24
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,7
58,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,6
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,8
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22

In [20]:
# Create a flag to assign loyalty based on max order value

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [21]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [22]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [23]:
# Check value counts

ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [25]:
# Check only select columns based on changes

ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

In [26]:
df_user_fifteen = ords_prods_merge[ords_prods_merge['user_id']==15]

In [27]:
df_user_fifteen

# Checks out as accurate aggregation, order of rows had impact on seeing complete results prior

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
51736,2514324,15,1,5,13,NaN,12427,2,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
51737,3135826,15,2,6,12,15.0,12427,2,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
51738,714991,15,4,1,11,16.0,12427,2,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
51739,3119091,15,8,2,17,8.0,12427,1,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
51740,2883598,15,12,1,8,6.0,12427,2,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Average orders,22,Regular customer
51741,113728,15,14,1,10,14.0,12427,3,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
51742,3097485,15,16,1,9,7.0,12427,2,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
51743,1870022,15,17,2,16,8.0,12427,2,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
51744,2345592,15,19,5,11,3.0,12427,4,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
51745,2994589,15,20,1,13,10.0,12427,1,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9516085,2514324,15,1,5,13,NaN,11266,1,0,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9516086,3135826,15,2,6,12,15.0,11266,4,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9516087,876095,15,6,5,11,8.0,11266,1,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9516088,2685110,15,7,1,11,17.0,11266,1,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9516089,887727,15,9,2,13,7.0,11266,2,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9516090,2600170,15,11,2,9,14.0,11266,2,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9516091,2332087,15,13,1,10,14.0,11266,2,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9516092,2968173,15,15,1,9,7.0,11266,1,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9516093,1870022,15,17,2,16,8.0,11266,1,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9516094,2345592,15,19,5,11,3.0,11266,1,1,Dried Mangos,117,19,3.6,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9520166,2514324,15,1,5,13,NaN,10441,3,0,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9520167,714991,15,4,1,11,16.0,10441,1,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9520168,887727,15,9,2,13,7.0,10441,3,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9520169,2600170,15,11,2,9,14.0,10441,3,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9520170,113728,15,14,1,10,14.0,10441,2,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9520171,3097485,15,16,1,9,7.0,10441,1,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9520172,1870022,15,17,2,16,8.0,10441,4,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9520173,487368,15,22,1,10,14.0,10441,2,1,Dry Roasted Almonds,117,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9523075,2514324,15,1,5,13,NaN,14715,4,0,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9523076,2564002,15,3,6,12,7.0,14715,1,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9523077,714991,15,4,1,11,16.0,14715,3,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9523078,3317979,15,5,4,15,17.0,14715,1,1,Coconut Water,98,7,4.0,both,Low-range product,Least busy,Slowest days,Most orders,22,Regular customer
9523079,2685110,15,7,1,11,17.0,14715,3,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9523080,887727,15,9,2,13,7.0,14715,1,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9523081,2600170,15,11,2,9,14.0,14715,1,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9523082,2332087,15,13,1,10,14.0,14715,3,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9523083,3097485,15,16,1,9,7.0,14715,4,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9523084,1870022,15,17,2,16,8.0,14715,3,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9523085,2994589,15,20,1,13,10.0,14715,3,1,Coconut Water,98,7,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9531923,3135826,15,2,6,12,15.0,37710,1,0,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9531924,3317979,15,5,4,15,17.0,37710,2,1,Trail Mix,125,19,2.1,both,Low-range product,Least busy,Slowest days,Most orders,22,Regular customer
9531925,876095,15,6,5,11,8.0,37710,2,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9531926,2570697,15,10,2,10,21.0,37710,1,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9531927,2600170,15,11,2,9,14.0,37710,4,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9531928,2332087,15,13,1,10,14.0,37710,1,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9531929,113728,15,14,1,10,14.0,37710,1,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9531930,1870022,15,17,2,16,8.0,37710,5,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9531931,2345592,15,19,5,11,3.0,37710,2,1,Trail Mix,125,19,2.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9543991,3135826,15,2,6,12,15.0,42862,3,0,Lemon Garlic Turkey Jerky,23,19,4.9,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9544012,3135826,15,2,6,12,15.0,27839,5,0,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9544013,2685110,15,7,1,11,17.0,27839,2,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9544014,2570697,15,10,2,10,21.0,27839,2,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9544015,2883598,15,12,1,8,6.0,27839,3,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Busiest days,Average orders,22,Regular customer
9544016,113728,15,14,1,10,14.0,27839,5,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9544017,2968173,15,15,1,9,7.0,27839,3,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9544018,2345592,15,19,5,11,3.0,27839,3,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9544019,2994589,15,20,1,13,10.0,27839,2,1,49 Flavors Jelly Belly Jelly Beans,45,19,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9545609,3317979,15,5,4,15,17.0,30292,3,0,Cola Cans,77,7,8.8,both,NaN,Least busy,Slowest days,Most orders,22,Regular customer
9545795,876095,15,6,5,11,8.0,37059,3,0,Lemon & Lime Blossom Ocean Fresh Scent Disinfe...,114,17,6.3,both,NaN,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9546357,2685110,15,7,1,11,17.0,48142,4,0,Diet,77,7,1.9,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9546358,2883598,15,12,1,8,6.0,48142,1,1,Diet,77,7,1.9,both,Low-range product,Regularly busy,Busiest days,Average orders,22,Regular customer
9546359,2715276,15,21,1,9,7.0,48142,2,1,Diet,77,7,1.9,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9549636,3119091,15,8,2,17,8.0,1747,2,0,Teriyaki Beef Jerky,23,19,3.3,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9549637,113728,15,14,1,10,14.0,1747,4,1,Teriyaki Beef Jerky,23,19,3.3,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9549638,3097485,15,16,1,9,7.0,1747,3,1,Teriyaki Beef Jerky,23,19,3.3,both,Low-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
9549639,2345592,15,19,5,11,3.0,1747,5,1,Teriyaki Beef Jerky,23,19,3.3,both,Low-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
9551084,2570697,15,10,2,10,21.0,43721,3,0,Wint-O-Green,46,19,5.4,both,NaN,Regularly busy,Regularly busy days,Most orders,22,Regular customer

## Export updated dataframe

In [28]:
# Export ords_prods_merge with aggregations

ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))